# Generated by Django 4.2.4 on 2023-09-05 21:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=8, verbose_name='D.N.I')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('vive', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('legajo', ckeditor.fields.RichTextField(default='legajo')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
